const FETCH_COLLECTIONS_SUCCESS = "FETCH_COLLECTIONS_SUCCESS";
const FETCH_COLLECTIONS_FAILURE = "FETCH_COLLECTIONS_FAILURE";
const ADD_COLLECTION_REQUEST = "ADD_COLLECTION_REQUEST";
const ADD_COLLECTION_SUCCESS = "ADD_COLLECTION_SUCCESS";
const ADD_COLLECTION_FAILURE = "ADD_COLLECTION_FAILURE";
const UPDATE_COLLECTION_REQUEST = "UPDATE_COLLECTION_REQUEST";
const UPDATE_COLLECTION_SUCCESS = "UPDATE_COLLECTION_SUCCESS";
const UPDATE_COLLECTION_FAILURE = "UPDATE_COLLECTION_FAILURE";
const DELETE_COLLECTION_REQUEST = "DELETE_COLLECTION_REQUEST";
const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
const DELETE_COLLECTION_FAILURE = "DELETE_COLLECTION_FAILURE";
const DUPLICATE_COLLECTION_SUCCESS = "DUPLICATE_COLLECTION_SUCCESS";
const DUPLICATE_COLLECTION_FAILURE = "DUPLICATE_COLLECTION_FAILURE";

export default {
  FETCH_COLLECTIONS_SUCCESS,
  FETCH_COLLECTIONS_FAILURE,
  ADD_COLLECTION_REQUEST,
  ADD_COLLECTION_SUCCESS,
  ADD_COLLECTION_FAILURE,
  UPDATE_COLLECTION_REQUEST,
  UPDATE_COLLECTION_SUCCESS,
  UPDATE_COLLECTION_FAILURE,
  DELETE_COLLECTION_REQUEST,
  DELETE_COLLECTION_SUCCESS,
  DELETE_COLLECTION_FAILURE,
  DUPLICATE_COLLECTION_SUCCESS,
  DUPLICATE_COLLECTION_FAILURE
};
