steps:
  # build the container image
  - id: "Build and Push Docker image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        echo "
        REACT_APP_UI_URL=$$HITMAN_UI_BASE_URL
        REACT_APP_API_URL=$$HITMAN_API_BASE_URL
        REACT_APP_UI_IP=$$REACT_APP_UI_IP
        REACT_APP_DOMAINS_LIST=$$REACT_APP_DOMAINS_LIST
        REACT_APP_CUSTOM_DOMAINS_LIST=$$REACT_APP_CUSTOM_DOMAINS_LIST
        REACT_APP_STEVE_WIDGET_URL=$$STEVE_WIDGET_URL
        REACT_APP_STEVE_PROJECT_ID=$$HITMAN_STEVE_PROJECT_ID
        REACT_APP_STEVE_AUTHKEY=$$HITMAN_STEVE_AUTHKEY
        REACT_APP_STEVE_WIDGET_ID=$$HITMAN_STEVE_WIDGET_ID
        REACT_APP_FEEDIO_UI_URL=$$FEEDIO_UI_BASE_URL
        REACT_APP_HELLO_WIDGET_TOKEN=$$HELLO_WIDGET_TOKEN
        REACT_APP_DESKTOP_APP_DOWNLOAD_LINK=$$REACT_APP_DESKTOP_APP_DOWNLOAD_LINK
        REACT_APP_PUBLIC_UI_URL=$$HITMAN_UI_PUBLIC_URL
        REACT_APP_AMPLITUDE_KEY=$$REACT_APP_AMPLITUDE_KEY
        REACT_APP_TINYMCE_API_KEY=$$REACT_APP_TINYMCE_API_KEY
        REACT_APP_TECHDOC_MAPPING_DOMAIN=$$REACT_APP_TECHDOC_MAPPING_DOMAIN
        " > .env 
        cat .env
        docker build -t asia.gcr.io/$PROJECT_ID/hitman-ui:$BUILD_ID --build-arg PRERENDER_TOKEN=$$PRERENDER_TOKEN .
        docker push asia.gcr.io/$PROJECT_ID/hitman-ui:$BUILD_ID

    # deploy container image to GKE
  - id: "Set Deployment image"
    name: "gcr.io/cloud-builders/kubectl"
    args: ["set", "image", "deployment/hitman-ui", "hitman-ui=asia.gcr.io/$PROJECT_ID/hitman-ui:$BUILD_ID", "-n", "viasocket"]
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-south1
      - CLOUDSDK_CONTAINER_CLUSTER=viasocket-gke-standard

options:
  logging: CLOUD_LOGGING_ONLY
  secretEnv:
    [
      "HITMAN_UI_BASE_URL",
      "HITMAN_API_BASE_URL",
      "REACT_APP_UI_IP",
      "REACT_APP_DOMAINS_LIST",
      "REACT_APP_CUSTOM_DOMAINS_LIST",
      "VIASOCKET_UI_BASE_URL",
      "STEVE_WIDGET_URL",
      "HITMAN_STEVE_PROJECT_ID",
      "HITMAN_STEVE_AUTHKEY",
      "HITMAN_STEVE_WIDGET_ID",
      "FEEDIO_UI_BASE_URL",
      "HELLO_WIDGET_TOKEN",
      "REACT_APP_DESKTOP_APP_DOWNLOAD_LINK",
      "HITMAN_UI_PUBLIC_URL",
      "HTTPDUMP_UI_BASE_URL",
      "CONTENTBASE_UI_BASE_URL",
      "REACT_APP_AMPLITUDE_KEY",
      "REACT_APP_TINYMCE_API_KEY",
      "REACT_APP_TECHDOC_MAPPING_DOMAIN",
      "PRERENDER_TOKEN"
    ]

timeout: 1200s
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/HITMAN_UI_BASE_URL/versions/latest
      env: "HITMAN_UI_BASE_URL"
    - versionName: projects/$PROJECT_ID/secrets/HITMAN_API_BASE_URL/versions/latest
      env: "HITMAN_API_BASE_URL"
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_UI_IP/versions/latest
      env: "REACT_APP_UI_IP"
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_DOMAINS_LIST/versions/latest
      env: "REACT_APP_DOMAINS_LIST"
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_CUSTOM_DOMAINS_LIST/versions/latest
      env: "REACT_APP_CUSTOM_DOMAINS_LIST"
    - versionName: projects/$PROJECT_ID/secrets/STEVE_WIDGET_URL/versions/latest
      env: "STEVE_WIDGET_URL"
    - versionName: projects/$PROJECT_ID/secrets/HITMAN_STEVE_PROJECT_ID/versions/latest
      env: "HITMAN_STEVE_PROJECT_ID"
    - versionName: projects/$PROJECT_ID/secrets/HITMAN_STEVE_AUTHKEY/versions/latest
      env: "HITMAN_STEVE_AUTHKEY"
    - versionName: projects/$PROJECT_ID/secrets/HITMAN_STEVE_WIDGET_ID/versions/latest
      env: "HITMAN_STEVE_WIDGET_ID"
    - versionName: projects/$PROJECT_ID/secrets/HELLO_WIDGET_TOKEN/versions/latest
      env: "HELLO_WIDGET_TOKEN"
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_DESKTOP_APP_DOWNLOAD_LINK/versions/latest
      env: "REACT_APP_DESKTOP_APP_DOWNLOAD_LINK"
    - versionName: projects/$PROJECT_ID/secrets/HITMAN_UI_PUBLIC_URL/versions/latest
      env: "HITMAN_UI_PUBLIC_URL"
    - versionName: projects/$PROJECT_ID/secrets/CONTENTBASE_UI_BASE_URL/versions/latest
      env: "CONTENTBASE_UI_BASE_URL"
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_AMPLITUDE_KEY/versions/latest
      env: "REACT_APP_AMPLITUDE_KEY"
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_TINYMCE_API_KEY/versions/latest
      env: "REACT_APP_TINYMCE_API_KEY"
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_TECHDOC_MAPPING_DOMAIN/versions/latest
      env: "REACT_APP_TECHDOC_MAPPING_DOMAIN"
    - versionName: projects/$PROJECT_ID/secrets/PRERENDER_TOKEN/versions/latest
      env: "PRERENDER_TOKEN"
