const ON_BULK_PUBLISH_UPDATION = 'ON_BULK_PUBLISH_UPDATION'
const ON_BULK_PUBLISH_UPDATION_ERROR = 'ON_BULK_PUBLISH_UPDATION_ERROR'

export default {
  ON_BULK_PUBLISH_UPDATION,
  ON_BULK_PUBLISH_UPDATION_ERROR
}
