const ON_BULK_PUBLISH_UPDATION = 'ON_BULK_PUBLISH_UPDATION'
const ON_BULK_PUBLISH_UPDATION_PAGES = 'ON_BULK_PUBLISH_UPDATION_PAGES'
const ON_BULK_PUBLISH_UPDATION_ERROR = 'ON_BULK_PUBLISH_UPDATION_ERROR'
const ON_BULK_PUBLISH_TABS = 'ON_BULK_PUBLISH_TABS'

export default {
  ON_BULK_PUBLISH_UPDATION,
  ON_BULK_PUBLISH_UPDATION_ERROR,
  ON_BULK_PUBLISH_TABS,
  ON_BULK_PUBLISH_UPDATION_PAGES
}