const ON_FETCH_ALL_TEAMS_OF_USER = "ON_FETCH_ALL_TEAMS_OF_USER";
const ON_FETCH_ALL_TEAMS_OF_USER_ERROR = "ON_FETCH_ALL_TEAMS_OF_USER_ERROR";

export default {
  ON_FETCH_ALL_TEAMS_OF_USER,
  ON_FETCH_ALL_TEAMS_OF_USER_ERROR
};
