const FETCH_ENVIRONMENTS_SUCCESS = "FETCH_ENVIRONMENTS_SUCCESS";
const FETCH_ENVIRONMENTS_FAILURE = "FETCH_ENVIRONMENTS_FAILURE";
const ADD_ENVIRONMENT_REQUEST = "ADD_ENVIRONMENT_REQUEST";
const ADD_ENVIRONMENT_SUCCESS = "ADD_ENVIRONMENT_SUCCESS";
const ADD_ENVIRONMENT_FAILURE = "ADD_ENVIRONMENT_FAILURE";
const UPDATE_ENVIRONMENT_REQUEST = "UPDATE_ENVIRONMENT_REQUEST";
const UPDATE_ENVIRONMENT_SUCCESS = "UPDATE_ENVIRONMENT_SUCCESS";
const UPDATE_ENVIRONMENT_FAILURE = "UPDATE_ENVIRONMENT_FAILURE";
const DELETE_ENVIRONMENT_REQUEST = "DELETE_ENVIRONMENT_REQUEST";
const DELETE_ENVIRONMENT_SUCCESS = "DELETE_ENVIRONMENT_SUCCESS";
const DELETE_ENVIRONMENT_FAILURE = "DELETE_ENVIRONMENT_FAILURE";

export default {
  FETCH_ENVIRONMENTS_SUCCESS,
  FETCH_ENVIRONMENTS_FAILURE,
  ADD_ENVIRONMENT_REQUEST,
  ADD_ENVIRONMENT_SUCCESS,
  ADD_ENVIRONMENT_FAILURE,
  UPDATE_ENVIRONMENT_REQUEST,
  UPDATE_ENVIRONMENT_SUCCESS,
  UPDATE_ENVIRONMENT_FAILURE,
  DELETE_ENVIRONMENT_REQUEST,
  DELETE_ENVIRONMENT_SUCCESS,
  DELETE_ENVIRONMENT_FAILURE
};
