const ON_VERSIONS_FETCHED = 'ON_VERSIONS_FETCHED'
const ON_VERSIONS_FETCHED_ERROR = 'ON_VERSIONS_FETCHED_ERROR'
const ADD_VERSION_REQUEST = 'ADD_VERSION_REQUEST'
const ON_VERSION_ADDED = 'ON_VERSION_ADDED'
const ON_VERSION_ADDED_ERROR = 'ON_VERSION_ADDED_ERROR'
const UPDATE_VERSION_REQUEST = 'UPDATE_VERSION_REQUEST'
const ON_VERSION_UPDATED = 'ON_VERSION_UPDATED'
const ON_VERSION_UPDATED_ERROR = 'ON_VERSION_UPDATED_ERROR'
const DELETE_VERSION_REQUEST = 'DELETE_VERSION_REQUEST'
const ON_VERSION_DELETED = 'ON_VERSION_DELETED'
const ON_VERSION_DELETED_ERROR = 'ON_VERSION_DELETED_ERROR'
const ON_VERSION_DUPLICATED = 'ON_VERSION_DUPLICATED'
const IMPORT_VERSION = 'IMPORT_VERSION'
const ON_AUTHORIZATION_RESPONSES_REQUEST = 'ON_AUTHORIZATION_RESPONSES_REQUEST'
const ON_AUTHORIZATION_RESPONSES_ERROR = 'ON_AUTHORIZATION_RESPONSES_ERROR'
const ON_AUTHORIZATION_DATA_REQUEST = 'ON_AUTHORIZATION_DATA_REQUEST'
const ON_AUTHORIZATION_DATA_ERROR = 'ON_AUTHORIZATION_DATA_ERROR'
const IMPORT_COLLECTION = 'IMPORT_COLLECTION'
const ON_VERSION_IMPORT_ERROR = 'ON_VERSION_IMPORT_ERROR'
const ON_PARENTPAGE_VERSION_ADDED ='ON_PARENTPAGE_VERSION_ADDED'

export default {
  ON_VERSIONS_FETCHED,
  ON_VERSIONS_FETCHED_ERROR,
  ADD_VERSION_REQUEST,
  ON_VERSION_ADDED,
  ON_VERSION_ADDED_ERROR,
  UPDATE_VERSION_REQUEST,
  ON_VERSION_UPDATED,
  ON_VERSION_UPDATED_ERROR,
  DELETE_VERSION_REQUEST,
  ON_VERSION_DELETED,
  ON_VERSION_DELETED_ERROR,
  ON_VERSION_DUPLICATED,
  IMPORT_VERSION,
  ON_AUTHORIZATION_RESPONSES_REQUEST,
  ON_AUTHORIZATION_RESPONSES_ERROR,
  ON_AUTHORIZATION_DATA_REQUEST,
  ON_AUTHORIZATION_DATA_ERROR,
  IMPORT_COLLECTION,
  ON_VERSION_IMPORT_ERROR,
  ON_PARENTPAGE_VERSION_ADDED
}
