const ON_COLLECTION_SHARED = "ON_COLLECTION_SHARED";
const ON_COLLECTION_SHARED_ERROR = "ON_COLLECTION_SHARED_ERROR";
const ON_FETCH_ALL_SHARED_USERS = "ON_FETCH_ALL_SHARED_USERS";
const ON_FETCH_ALL_SHARED_USERS_ERROR = "ON_FETCH_ALL_SHARED_USERS_ERROR";
const DELETE_SHARED_USERS_REQUEST = "DELETE_SHARED_USERS_REQUEST";
const ON_SHARED_USERS_DELETED = "ON_SHARED_USERS_DELETED";
const ON_SHARED_USERS_DELETED_ERROR = "ON_SHARED_USERS_DELETED_ERROR";

export default {
  ON_COLLECTION_SHARED,
  ON_COLLECTION_SHARED_ERROR,
  ON_FETCH_ALL_SHARED_USERS,
  ON_FETCH_ALL_SHARED_USERS_ERROR,
  DELETE_SHARED_USERS_REQUEST,
  ON_SHARED_USERS_DELETED,
  ON_SHARED_USERS_DELETED_ERROR
};
