const ADD_DOMAIN_REQUEST = 'ADD_DOMAIN_REQUEST'
const ON_DOMAIN_ADDED = 'ON_DOMAIN_ADDED'
const ON_DOMAIN_ADDED_ERROR = 'ON_DOMAIN_ADDED_ERROR'
const ON_COOKIES_FETCHED = 'ON_COOKIES_FETCHED'
const ON_COOKIES_FETCHED_ERROR = 'ON_COOKIES_FETCHED_ERROR'

export default {
  ADD_DOMAIN_REQUEST,
  ON_DOMAIN_ADDED,
  ON_DOMAIN_ADDED_ERROR,
  ON_COOKIES_FETCHED,
  ON_COOKIES_FETCHED_ERROR
}