version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@1.1.0
  gcr: circleci/gcp-gcr@0.0.2
  slack: circleci/slack@4.1
jobs:
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - run:
          name: Add Environment Variables
          command: |
            echo "
            REACT_APP_UI_URL=$REACT_APP_UI_URL
            REACT_APP_API_URL= $REACT_APP_API_URL
            REACT_APP_SOCKET_SSO_URL= $REACT_APP_SOCKET_SSO_URL
            REACT_APP_UI_IP= $REACT_APP_UI_IP
            REACT_APP_DOMAINS_LIST= $REACT_APP_DOMAINS_LIST
            REACT_APP_CUSTOM_DOMAINS_LIST= $REACT_APP_CUSTOM_DOMAINS_LIST
            REACT_APP_CIRCLECI_TOKEN= $REACT_APP_CIRCLECI_TOKEN
            REACT_APP_CIRCLECI_CONTEXT_ID= $REACT_APP_CIRCLECI_CONTEXT_ID
            REACT_APP_SIGN_UP_NOTIFIER_URL=$REACT_APP_SIGN_UP_NOTIFIER_URL
            REACT_APP_VIASOCKET_URL=$REACT_APP_VIASOCKET_URL
            REACT_APP_FEEDIO_BOARD_NAME=$REACT_APP_FEEDIO_BOARD_NAME
            REACT_APP_FEEDIO_HOST_NAME=$REACT_APP_FEEDIO_HOST_NAME
            REACT_APP_FEEDIO_BOARD_TOKEN=$REACT_APP_FEEDIO_BOARD_TOKEN
            REACT_APP_COMMUNITY_URL=$REACT_APP_COMMUNITY_URL

            " > .env
      - gcr/gcr-auth
      - run:
          name: Build Docker Image
          command: |
            docker build -t asia.gcr.io/$GOOGLE_PROJECT_ID/hitman-ui:<< pipeline.number >> .
      - run:
          name: Push image to GCR
          command: |
            docker push asia.gcr.io/$GOOGLE_PROJECT_ID/hitman-ui:<< pipeline.number >>

  Deploy-to-GKE:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Initialize the `gcloud` CLI.
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: $GOOGLE_CLUSTER_ID
          perform-login: true

      - add_ssh_keys:
          fingerprints:
            - $GOOGLE_SSH_KEY

      # Update a deployment Docker image.
      - run:
          name: Set Image
          command: |
            ssh $GOOGLE_SSH_USER@$GOOGLE_SSH_IP -p $GOOGLE_SSH_PORT "sudo su -c 'kubectl set image deployment/hitman-ui hitman-ui=asia.gcr.io/$GOOGLE_PROJECT_ID/hitman-ui:<< pipeline.number >> -n viasocket '"

      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1

      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Job Succeeded. :white_check_mark:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Job*: ${CIRCLE_JOB}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*:\n $CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*:\n $CIRCLE_BRANCH"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*:\n $CIRCLE_SHA1"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*:\n $CIRCLE_USERNAME"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                    "alt_text": "CircleCI logo"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }

workflows:
  Build_Deploy_Dev:
    jobs:
      - Build-Push-Image-Docker:
          filters:
            branches:
              only:
                - master
          context:
            - gke-dev
            - hitman-ui-dev

      - Deploy-to-GKE:
          requires:
            - Build-Push-Image-Docker
          filters:
            branches:
              only:
                - master
          context:
            - gke-dev
            - hitman-ui-dev

  Build_Deploy_Prod:
    jobs:
      - Build-Push-Image-Docker:
          filters:
            branches:
              only:
                - prod
          context:
            - prod
            - hitman-ui-prod

      - slack/on-hold:
          context:
            - prod
            - hitman-ui-prod
          requires:
            - Build-Push-Image-Docker
      - hold:
          type: approval
          requires:
            - Build-Push-Image-Docker
            - slack/on-hold

      - Deploy-to-GKE:
          requires:
            - hold
          filters:
            branches:
              only:
                - prod
          context:
            - prod
            - hitman-ui-prod

  # Build_Deploy_Prod_Auto:
  #   jobs:
  #     - Build-Push-Image-Docker:
  #         filters:
  #           branches:
  #             only:
  #               - prod
  #         context:
  #           - gke-prod
  #           - hitman-ui-prod-auto

  #     - hold:
  #         type: approval
  #         requires:
  #           - Build-Push-Image-Docker

  #     - Deploy-to-GKE:
  #         requires:
  #           - hold
  #         filters:
  #           branches:
  #             only:
  #               - prod
  #         context:
  #           - gke-prod
  #           - hitman-ui-prod-auto
