const ON_PAGES_FETCHED = 'ON_PAGES_FETCHED'
const ON_PAGES_FETCHED_ERROR = 'ON_PAGES_FETCHED_ERROR'
const ON_PAGE_FETCHED = 'ON_PAGE_FETCHED'
const ON_PAGE_FETCHED_ERROR = 'ON_PAGE_FETCHED_ERROR'
const ADD_PAGE_REQUEST = 'ADD_PAGE_REQUEST'
const ON_PAGE_ADDED = 'ON_PAGE_ADDED'
const ON_PAGE_ADDED_ERROR = 'ON_PAGE_ADDED_ERROR'
const ADD_GROUP_PAGE_REQUEST = 'ADD_GROUP_PAGE_REQUEST'
const ON_GROUP_PAGE_ADDED = 'ON_GROUP_PAGE_ADDED'
const ON_GROUP_PAGE_ADDED_ERROR = 'ON_GROUP_PAGE_ADDED_ERROR'
const UPDATE_PAGE_REQUEST = 'UPDATE_PAGE_REQUEST'
const ON_PAGE_UPDATED = 'ON_PAGE_UPDATED'
const ON_PAGE_UPDATED_ERROR = 'ON_PAGE_UPDATED_ERROR'
const DELETE_PAGE_REQUEST = 'DELETE_PAGE_REQUEST'
const ON_PAGE_DELETED = 'ON_PAGE_DELETED'
const ON_PAGE_DELETED_ERROR = 'ON_PAGE_DELETED_ERROR'
const ON_PAGE_DUPLICATED = 'ON_PAGE_DUPLICATED'
const ON_PAGES_ORDER_UPDATED = 'ON_PAGES_ORDER_UPDATED:'
const ON_PAGES_ORDER_UPDATED_ERROR = 'ON_PAGES_ORDER_UPDATED_ERROR'
const ADD_PARENT_PAGE_REQUEST = 'ADD_PARENT_PAGE_REQUEST'
const ON_PARENT_PAGE_ADDED = 'ON_PARENT_PAGE_ADDED'
const ON_EXPAND_PAGES = 'ON_EXPAND_PAGES'

export default {
  ON_PAGES_FETCHED,
  ON_PAGES_FETCHED_ERROR,
  ON_PAGE_FETCHED,
  ON_PAGE_FETCHED_ERROR,
  ADD_PAGE_REQUEST,
  ON_PAGE_ADDED,
  ON_PAGE_ADDED_ERROR,
  ADD_GROUP_PAGE_REQUEST,
  ADD_PARENT_PAGE_REQUEST,
  ON_PARENT_PAGE_ADDED,
  ON_GROUP_PAGE_ADDED,
  ON_GROUP_PAGE_ADDED_ERROR,
  UPDATE_PAGE_REQUEST,
  ON_PAGE_UPDATED,
  ON_PAGE_UPDATED_ERROR,
  DELETE_PAGE_REQUEST,
  ON_PAGE_DELETED,
  ON_PAGE_DELETED_ERROR,
  ON_PAGE_DUPLICATED,
  ON_PAGES_ORDER_UPDATED,
  ON_PAGES_ORDER_UPDATED_ERROR,
  ON_EXPAND_PAGES
}
