const ON_PUBLIC_ENDPOINTS_FETCHED = "ON_PUBLIC_ENDPOINTS_FETCHED";
const ON_PUBLIC_ENDPOINTS_FETCHED_ERROR = "ON_PUBLIC_ENDPOINTS_FETCHED_ERROR";

export default {
  ON_PUBLIC_ENDPOINTS_FETCHED,
  ON_PUBLIC_ENDPOINTS_FETCHED_ERROR
};
