const ON_PUBLIC_ENDPOINTS_FETCHED = "ON_PUBLIC_ENDPOINTS_FETCHED";
const ON_PUBLIC_ENDPOINTS_FETCHED_ERROR = "ON_PUBLIC_ENDPOINTS_FETCHED_ERROR";
const ON_PENDING_ENDPOINT_SUCCESS = "ON_PENDING_ENDPOINT_SUCCESS";
const ON_PENDING_ENDPOINT_ERROR = "ON_PENDING_ENDPOINT_ERROR";
const ON_APPROVED_ENDPOINT_SUCCESS = "ON_APPROVED_ENDPOINT_SUCCESS";
const ON_APPROVED_ENDPOINT_ERROR = "ON_APPROVED_ENDPOINT_ERROR";
const ON_REJECT_ENDPOINT_SUCCESS = "ON_REJECT_ENDPOINT_SUCCESS";
const ON_REJECT_ENDPOINT_ERROR = "ON_REJECT_ENDPOINT_ERROR";
const ON_DRAFT_ENDPOINT_SUCCESS = "ON_DRAFT_ENDPOINT_SUCCESS";
const ON_DRAFT_ENDPOINT_ERROR = "ON_DRAFT_ENDPOINT_ERROR";

export default {
  ON_PUBLIC_ENDPOINTS_FETCHED,
  ON_PUBLIC_ENDPOINTS_FETCHED_ERROR,
  ON_PENDING_ENDPOINT_SUCCESS,
  ON_PENDING_ENDPOINT_ERROR,
  ON_APPROVED_ENDPOINT_SUCCESS,
  ON_APPROVED_ENDPOINT_ERROR,
  ON_REJECT_ENDPOINT_SUCCESS,
  ON_REJECT_ENDPOINT_ERROR,
  ON_DRAFT_ENDPOINT_SUCCESS,
  ON_DRAFT_ENDPOINT_ERROR
};
