const ON_RESPONSE_TOGGLE = "ON_RESPONSE_TOGGLE"
// const ON_ASK_RESPONSE_TOGGLE = 'ON_ASK_RESPONSE_TOGGLE'
const ON_HISTORY_TOGGLE = "ON_HISTORY_TOGGLE"
const toggleResponseActionTypes = {
  ON_RESPONSE_TOGGLE,
  // ON_ASK_RESPONSE_TOGGLE,
  // ON_HISTORY_TOGGLE
}

export default toggleResponseActionTypes
