const ADD_IS_EXPANDED = "ADD_IS_EXPANDED"
const DEFAULT_VERSION_ID = "DEFAULT_VERSION_ID"
const UPDATE_FOR_ISPUBLISH = "UPDATE_FOR_ISPUBLISH"
const SET_COLLECTION_ID_FOR_PUBLISH = "SET_COLLECTION_ID_FOR_PUBLISH"

export default {
  ADD_IS_EXPANDED,
  DEFAULT_VERSION_ID,
  UPDATE_FOR_ISPUBLISH,
  SET_COLLECTION_ID_FOR_PUBLISH,
}
