const FETCH_PAGES_SUCCESS = "FETCH_PAGES_SUCCESS";
const FETCH_PAGES_FAILURE = "FETCH_PAGES_FAILURE";
const ADD_PAGE_REQUEST = "ADD_PAGE_REQUEST";
const ADD_PAGE_SUCCESS = "ADD_PAGE_SUCCESS";
const ADD_PAGE_FAILURE = "ADD_PAGE_FAILURE";
const UPDATE_PAGE_REQUEST = "UPDATE_PAGE_REQUEST";
const UPDATE_PAGE_SUCCESS = "UPDATE_PAGE_SUCCESS";
const UPDATE_PAGE_FAILURE = "UPDATE_PAGE_FAILURE";
const DELETE_PAGE_REQUEST = "DELETE_PAGE_REQUEST";
const DELETE_PAGE_SUCCESS = "DELETE_PAGE_SUCCESS";
const DELETE_PAGE_FAILURE = "DELETE_PAGE_FAILURE";

export default {
  FETCH_PAGES_SUCCESS,
  FETCH_PAGES_FAILURE,
  ADD_PAGE_REQUEST,
  ADD_PAGE_SUCCESS,
  ADD_PAGE_FAILURE,
  UPDATE_PAGE_REQUEST,
  UPDATE_PAGE_SUCCESS,
  UPDATE_PAGE_FAILURE,
  DELETE_PAGE_REQUEST,
  DELETE_PAGE_SUCCESS,
  DELETE_PAGE_FAILURE
};
