const ADD_COLLECTIONS_AND_PAGE_ON_SIDEBAR = 'ADD_COLLECTIONS_AND_PAGE_ON_SIDEBAR'
const ADD_COLLECTIONS_AND_PAGE_LOADING = 'ADD_COLLECTIONS_AND_PAGE_LOADING'

const sidebarV2ActionTypes = {
    ADD_COLLECTIONS_AND_PAGE_ON_SIDEBAR,
    ADD_COLLECTIONS_AND_PAGE_LOADING,
}

export default sidebarV2ActionTypes