const ADD_COLLECTIONS_AND_PAGE_ON_SIDEBAR = 'ADD_COLLECTIONS_AND_PAGE_ON_SIDEBAR'
const ADD_COLLECTIONS_AND_PAGE_LOADING = 'ADD_COLLECTIONS_AND_PAGE_LOADING'
const UPDATE_CLIENT_DATA_ISEXPANDED = 'UPDATE_CLIENT_DATA_ISEXPANDED'
const UPDATE_COLLECTION_IN_SIDEBAR ='UPDATE_COLLECTION_IN_SIDEBAR'

const sidebarV2ActionTypes = {
    ADD_COLLECTIONS_AND_PAGE_ON_SIDEBAR,
    ADD_COLLECTIONS_AND_PAGE_LOADING,
    UPDATE_CLIENT_DATA_ISEXPANDED,
    UPDATE_COLLECTION_IN_SIDEBAR
}

export default sidebarV2ActionTypes