const FOCUS_PREVIOUS_ITEM = 'SIDEBAR: FOCUS_PREVIOUS_ITEM'
const FOCUS_NEXT_ITEM = 'SIDEBAR: FOCUS_NEXT_ITEM'
const EXPAND_ITEM = 'SIDEBAR: EXPAND_CURRENT_ITEM'
const COLLAPSE_ITEM = 'SIDEBAR: COLLAPSE_CURRENT_ITEM'
const FOCUS_ITEM = 'SIDEBAR: FOCUS_ITEM'
const FOCUS_SIDEBAR = 'SIDEBAR: FOCUS'
const DEFOCUS_SIDEBAR = 'SIDEBAR: DEFOCUS'

const sidebarActionTypes = {
  FOCUS_SIDEBAR,
  DEFOCUS_SIDEBAR,
  FOCUS_ITEM,
  FOCUS_PREVIOUS_ITEM,
  FOCUS_NEXT_ITEM,
  EXPAND_ITEM,
  COLLAPSE_ITEM
}

export default sidebarActionTypes
