const ADD_NEW_TAB = 'ADD_NEW_TAB'
const CLOSE_TAB = 'CLOSE_TAB'
const UPDATE_TAB = 'UPDATE_TAB'
const UPDATE_TAB_DRAFT = 'UPDATE_TAB_DRAFT'
const OPEN_IN_NEW_TAB = 'OPEN_IN_NEW_TAB'
const SET_ACTIVE_TAB_ID = 'SET_ACTIVE_TAB_ID'
const SET_TABS_ORDER = 'SET_TABS_ORDER'
const FETCH_TABS_FROM_REDUX = 'FETCH_TABS_FROM_REDUX'
const REPLACE_TAB = 'REPLACE_TAB'
const CLOSE_ALL_TABS = 'CLOSE_ALL_TABS'
const REPLACE_TAB_ID = 'REPLACE_TAB_ID'

export default {
  ADD_NEW_TAB,
  CLOSE_TAB,
  UPDATE_TAB,
  UPDATE_TAB_DRAFT,
  OPEN_IN_NEW_TAB,
  SET_ACTIVE_TAB_ID,
  SET_TABS_ORDER,
  FETCH_TABS_FROM_REDUX,
  REPLACE_TAB,
  CLOSE_ALL_TABS,
  REPLACE_TAB_ID
}
