const FETCH_VERSIONS_SUCCESS = "FETCH_VERSIONS_SUCCESS";
const FETCH_VERSIONS_FAILURE = "FETCH_VERSIONS_FAILURE";
const ADD_VERSION_REQUEST = "ADD_VERSION_REQUEST";
const ADD_VERSION_SUCCESS = "ADD_VERSION_SUCCESS";
const ADD_VERSION_FAILURE = "ADD_VERSION_FAILURE";
const UPDATE_VERSION_REQUEST = "UPDATE_VERSION_REQUEST";
const UPDATE_VERSION_SUCCESS = "UPDATE_VERSION_SUCCESS";
const UPDATE_VERSION_FAILURE = "UPDATE_VERSION_FAILURE";
const DELETE_VERSION_REQUEST = "DELETE_VERSION_REQUEST";
const DELETE_VERSION_SUCCESS = "DELETE_VERSION_SUCCESS";
const DELETE_VERSION_FAILURE = "DELETE_VERSION_FAILURE";
const DUPLICATE_VERSION_SUCCESS = "DUPLICATE_VERSION_SUCCESS";
const DUPLICATE_VERSION_FAILURE = "DUPLICATE_VERSION_FAILURE";

const UPDATE_STATE_SUCCESS = "UPDATE_STATE_SUCCESS";
const UPDATE_STATE_FAILURE = "UPDATE_STATE_FAILURE";

export default {
  FETCH_VERSIONS_SUCCESS,
  FETCH_VERSIONS_FAILURE,
  ADD_VERSION_REQUEST,
  ADD_VERSION_SUCCESS,
  ADD_VERSION_FAILURE,
  UPDATE_VERSION_REQUEST,
  UPDATE_VERSION_SUCCESS,
  UPDATE_VERSION_FAILURE,
  DELETE_VERSION_REQUEST,
  DELETE_VERSION_SUCCESS,
  DELETE_VERSION_FAILURE,
  DUPLICATE_VERSION_SUCCESS,
  DUPLICATE_VERSION_FAILURE,
  UPDATE_STATE_SUCCESS,
  UPDATE_STATE_FAILURE
};
