const ON_FEEDBACKS_FETCHED = 'ON_FEEDBACKS_FETCHED'
const ON_FEEDBACKS_FETCHED_ERROR = 'ON_FEEDBACKS_FETCHED_ERROR'
const ON_SUBMIT_API_REVIEW = 'SUBMIT_API_REVIEW'
const ON_SUBMIT_API_REVIEW_ERROR = 'ON_SUBMIT_API_REVIEW_ERROR'

export default {
  ON_FEEDBACKS_FETCHED,
  ON_FEEDBACKS_FETCHED_ERROR,
  ON_SUBMIT_API_REVIEW,
  ON_SUBMIT_API_REVIEW_ERROR
}
