const ON_FEEDBACKS_FETCHED = 'ON_FEEDBACKS_FETCHED'
const ON_FEEDBACKS_FETCHED_ERROR = 'ON_FEEDBACKS_FETCHED_ERROR'
const ON_DEFAULT_VERSION = 'ON_DEFAULT_VERSION'
const ON_DEFAULT_VERSION_ERROR = 'ON_DEFAULT_VERSION_ERROR'

export default {
  ON_FEEDBACKS_FETCHED,
  ON_FEEDBACKS_FETCHED_ERROR,
  ON_DEFAULT_VERSION,
  ON_DEFAULT_VERSION_ERROR
}
