import NavigationSetter from "src/history";
import Providers from "../providers/providers";

export const metadata = {
    title: "Techdoc",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <Providers>
                {children}
            </Providers>
            <NavigationSetter />
        </>
    );
}