const FETCH_ENDPOINTS_SUCCESS = "FETCH_ENDPOINTS_SUCCESS";
const FETCH_ENDPOINTS_FAILURE = "FETCH_ENDPOINTS_FAILURE";
const ADD_ENDPOINT_REQUEST = "ADD_ENDPOINT_REQUEST";
const ADD_ENDPOINT_SUCCESS = "ADD_ENDPOINT_SUCCESS";
const ADD_ENDPOINT_FAILURE = "ADD_ENDPOINT_FAILURE";
const UPDATE_ENDPOINT_REQUEST = "UPDATE_ENDPOINT_REQUEST";
const UPDATE_ENDPOINT_SUCCESS = "UPDATE_ENDPOINT_SUCCESS";
const UPDATE_ENDPOINT_FAILURE = "UPDATE_ENDPOINT_FAILURE";
const DELETE_ENDPOINT_REQUEST = "DELETE_ENDPOINT_REQUEST";
const DELETE_ENDPOINT_SUCCESS = "DELETE_ENDPOINT_SUCCESS";
const DELETE_ENDPOINT_FAILURE = "DELETE_ENDPOINT_FAILURE";
const DUPLICATE_ENDPOINT_SUCCESS = "DUPLICATE_ENDPOINT_SUCCESS";
const DUPLICATE_ENDPOINT_FAILURE = "DUPLICATE_ENDPOINT_FAILURE";

const UPDATE_STATE_SUCCESS = "UPDATE_STATE_SUCCESS";
const UPDATE_STATE_FAILURE = "UPDATE_STATE_FAILURE";
export default {
  FETCH_ENDPOINTS_SUCCESS,
  FETCH_ENDPOINTS_FAILURE,
  ADD_ENDPOINT_REQUEST,
  ADD_ENDPOINT_SUCCESS,
  ADD_ENDPOINT_FAILURE,
  UPDATE_ENDPOINT_REQUEST,
  UPDATE_ENDPOINT_SUCCESS,
  UPDATE_ENDPOINT_FAILURE,
  DELETE_ENDPOINT_REQUEST,
  DELETE_ENDPOINT_SUCCESS,
  DELETE_ENDPOINT_FAILURE,
  DUPLICATE_ENDPOINT_FAILURE,
  DUPLICATE_ENDPOINT_SUCCESS,
  UPDATE_STATE_SUCCESS,
  UPDATE_STATE_FAILURE
};
