const ON_ENDPOINTS_FETCHED = "ON_ENDPOINTS_FETCHED";
const ON_ENDPOINTS_FETCHED_ERROR = "ON_ENDPOINTS_FETCHED_ERROR";
const ADD_ENDPOINT_REQUEST = "ADD_ENDPOINT_REQUEST";
const ON_ENDPOINT_ADDED = "ON_ENDPOINT_ADDED";
const ON_ENDPOINT_ADDED_ERROR = "ON_ENDPOINT_ADDED_ERROR";
const UPDATE_ENDPOINT_REQUEST = "UPDATE_ENDPOINT_REQUEST";
const ON_ENDPOINT_UPDATED = "ON_ENDPOINT_UPDATED";
const ON_ENDPOINT_UPDATED_ERROR = "ON_ENDPOINT_UPDATED_ERROR";
const DELETE_ENDPOINT_REQUEST = "DELETE_ENDPOINT_REQUEST";
const ON_ENDPOINT_DELETED = "ON_ENDPOINT_DELETED";
const ON_ENDPOINT_DELETED_ERROR = "ON_ENDPOINT_DELETED_ERROR";
const ON_ENDPOINT_DUPLICATED = "ON_ENDPOINT_DUPLICATED";
const ON_ENDPOINT_DUPLICATED_ERROR = "ON_ENDPOINT_DUPLICATED_ERROR";

const UPDATE_STATE_SUCCESS = "UPDATE_STATE_SUCCESS";
const UPDATE_STATE_FAILURE = "UPDATE_STATE_FAILURE";
export default {
  ON_ENDPOINTS_FETCHED,
  ON_ENDPOINTS_FETCHED_ERROR,
  ADD_ENDPOINT_REQUEST,
  ON_ENDPOINT_ADDED,
  ON_ENDPOINT_ADDED_ERROR,
  UPDATE_ENDPOINT_REQUEST,
  ON_ENDPOINT_UPDATED,
  ON_ENDPOINT_UPDATED_ERROR,
  DELETE_ENDPOINT_REQUEST,
  ON_ENDPOINT_DELETED,
  ON_ENDPOINT_DELETED_ERROR,
  ON_ENDPOINT_DUPLICATED,
  ON_ENDPOINT_DUPLICATED_ERROR,
  UPDATE_STATE_SUCCESS,
  UPDATE_STATE_FAILURE
};
