const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
const FETCH_GROUPS_FAILURE = "FETCH_GROUPS_FAILURE";
const ADD_GROUP_REQUEST = "ADD_GROUP_REQUEST";
const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS";
const ADD_GROUP_FAILURE = "ADD_GROUP_FAILURE";
const UPDATE_GROUP_REQUEST = "UPDATE_GROUP_REQUEST";
const UPDATE_GROUP_SUCCESS = "UPDATE_GROUP_SUCCESS";
const UPDATE_GROUP_FAILURE = "UPDATE_GROUP_FAILURE";
const DELETE_GROUP_REQUEST = "DELETE_GROUP_REQUEST";
const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";
const DELETE_GROUP_FAILURE = "DELETE_GROUP_FAILURE";

export default {
  FETCH_GROUPS_SUCCESS,
  FETCH_GROUPS_FAILURE,
  ADD_GROUP_REQUEST,
  ADD_GROUP_SUCCESS,
  ADD_GROUP_FAILURE,
  UPDATE_GROUP_REQUEST,
  UPDATE_GROUP_SUCCESS,
  UPDATE_GROUP_FAILURE,
  DELETE_GROUP_REQUEST,
  DELETE_GROUP_SUCCESS,
  DELETE_GROUP_FAILURE
};
