const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
const FETCH_GROUPS_FAILURE = "FETCH_GROUPS_FAILURE";
const ADD_GROUPS_REQUEST = "ADD_GROUPS_REQUEST";
const ADD_GROUPS_SUCCESS = "ADD_GROUPS_SUCCESS";
const ADD_GROUPS_FAILURE = "ADD_GROUPS_FAILURE";
const UPDATE_GROUPS_REQUEST = "UPDATE_GROUPS_REQUEST";
const UPDATE_GROUPS_SUCCESS = "UPDATE_GROUPS_SUCCESS";
const UPDATE_GROUPS_FAILURE = "UPDATE_GROUPS_FAILURE";
const DELETE_GROUPS_REQUEST = "DELETE_GROUPS_REQUEST";
const DELETE_GROUPS_SUCCESS = "DELETE_GROUPS_SUCCESS";
const DELETE_GROUPS_FAILURE = "DELETE_GROUPS_FAILURE";

export default {
  FETCH_GROUPS_SUCCESS,
  FETCH_GROUPS_FAILURE,
  ADD_GROUPS_REQUEST,
  ADD_GROUPS_SUCCESS,
  ADD_GROUPS_FAILURE,
  UPDATE_GROUPS_REQUEST,
  UPDATE_GROUPS_SUCCESS,
  UPDATE_GROUPS_FAILURE,
  DELETE_GROUPS_REQUEST,
  DELETE_GROUPS_SUCCESS,
  DELETE_GROUPS_FAILURE
};
