const ON_GROUPS_FETCHED = "ON_GROUPS_FETCHED";
const ON_GROUPS_FETCHED_ERROR = "ON_GROUPS_FETCHED_ERROR";
const ADD_GROUP_REQUEST = "ADD_GROUP_REQUEST";
const ON_GROUP_ADDED = "ON_GROUP_ADDED";
const ON_GROUP_ADDED_ERROR = "ON_GROUP_ADDED_ERROR";
const UPDATE_GROUP_REQUEST = "UPDATE_GROUP_REQUEST";
const ON_GROUP_UPDATED = "ON_GROUP_UPDATED";
const ON_GROUP_UPDATED_ERROR = "ON_GROUP_UPDATED_ERROR";
const DELETE_GROUP_REQUEST = "DELETE_GROUP_REQUEST";
const ON_GROUP_DELETED = "ON_GROUP_DELETED";
const ON_GROUP_DELETED_ERROR = "ON_GROUP_DELETED_ERROR";

const ON_GROUP_DUPLICATED = "ON_GROUP_DUPLICATED";
const ON_GROUP_DUPLICATED_ERROR = "ON_GROUP_DUPLICATED_ERROR";

const UPDATE_STATE_SUCCESS = "UPDATE_STATE_SUCCESS";
const UPDATE_STATE_FAILURE = "UPDATE_STATE_FAILURE";
export default {
  ON_GROUPS_FETCHED,
  ON_GROUPS_FETCHED_ERROR,
  ADD_GROUP_REQUEST,
  ON_GROUP_ADDED,
  ON_GROUP_ADDED_ERROR,
  UPDATE_GROUP_REQUEST,
  ON_GROUP_UPDATED,
  ON_GROUP_UPDATED_ERROR,
  DELETE_GROUP_REQUEST,
  ON_GROUP_DELETED,
  ON_GROUP_DELETED_ERROR,
  ON_GROUP_DUPLICATED,
  ON_GROUP_DUPLICATED_ERROR,
  UPDATE_STATE_SUCCESS,
  UPDATE_STATE_FAILURE
};
