name: Deployment
on:
  push:
    branches: [test, prod]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: ${{github.ref_name}}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.17"
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm i --legacy-peer-deps
      - name: Build
        env:
          CI: false
          NEXT_PUBLIC_ANALYSIS_KEY: ${{ vars.NEXT_PUBLIC_ANALYSIS_KEY }}
          NEXT_PUBLIC_API_URL : ${{vars.NEXT_PUBLIC_API_URL}}
          NEXT_PUBLIC_UI_URL : ${{vars.NEXT_PUBLIC_UI_URL}}
          NEXT_PUBLIC_UI_IP: ${{vars.NEXT_PUBLIC_UI_IP}}
          NEXT_PUBLIC_DOMAINS_LIST: ${{vars.NEXT_PUBLIC_DOMAINS_LIST}}
          NEXT_PUBLIC_CUSTOM_DOMAINS_LIST: ${{vars.NEXT_PUBLIC_CUSTOM_DOMAINS_LIST}}
          NEXT_PUBLIC_ANALYTICS: ${{vars.NEXT_PUBLIC_ANALYTICS}}
          NEXT_PUBLIC_ENV: ${{vars.NEXT_PUBLIC_ENV}}

          #Proxy URLs
          NEXT_PUBLIC_PROXY_URL : ${{vars.NEXT_PUBLIC_PROXY_URL}}
          NEXT_PUBLIC_PROXY_REFERENCE_ID_LOCAL : ${{vars.NEXT_PUBLIC_PROXY_REFERENCE_ID_LOCAL}}
          NEXT_PUBLIC_PROXY_REFERENCE_ID_TEST : ${{vars.NEXT_PUBLIC_PROXY_REFERENCE_ID_TEST}}
          NEXT_PUBLIC_PROXY_REFERENCE_ID_PROD : ${{vars.NEXT_PUBLIC_PROXY_REFERENCE_ID_PROD}}
          
          # URL for which only non logged in user dashboard route and all public routes will be opened.
          NEXT_PUBLIC_PUBLIC_UI_URL: ${{vars.NEXT_PUBLIC_PUBLIC_UI_URL}}
          
          #steve_onboarding_widget
          NEXT_PUBLIC_STEVE_WIDGET_URL: ${{vars.NEXT_PUBLIC_STEVE_WIDGET_URL}}
          NEXT_PUBLIC_STEVE_PROJECT_ID: ${{vars.YOUR_STEVE_PROJECT_ID}}
          NEXT_PUBLIC_STEVE_AUTHKEY: ${{vars.YOUR_STEVE_AUTHKEY}}
          NEXT_PUBLIC_STEVE_WIDGET_ID: ${{vars.YOUR_STEVE_WIDGET_ID}}
          
          #HELLO_WIDGET
          NEXT_PUBLIC_HELLO_WIDGET_TOKEN : ${{vars.NEXT_PUBLIC_HELLO_WIDGET_TOKEN}}
          
          # Desktop App Urls
          NEXT_PUBLIC_DESKTOP_APP_DOWNLOAD_LINK : ${{vars.NEXT_PUBLIC_DESKTOP_APP_DOWNLOAD_LINK}}
          
          # Notarize credentials
          NOTARIZE_EMAIL: ${{vars.NOTARIZE_EMAIL}}
          NOTARIZE_PASS: ${{vars.NOTARIZE_PASS}}
          
          #AMPLITUDE
          NEXT_PUBLIC_AMPLITUDE_KEY : ${{vars.NEXT_PUBLIC_AMPLITUDE_KEY}}

          NEXT_PUBLIC_TINYMCE_API_KEY : ${{vars.NEXT_PUBLIC_TINYMCE_API_KEY}}
          NEXT_PUBLIC_TECHDOC_MAPPING_DOMAIN : ${{vars.NEXT_PUBLIC_TECHDOC_MAPPING_DOMAIN}}

          NEXT_PUBLIC_RTLAYER_OID : ${{vars.NEXT_PUBLIC_RTLAYER_OID}}
          NEXT_PUBLIC_RTLAYER_SID : ${{vars.NEXT_PUBLIC_RTLAYER_SID}}


        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: ${{github.ref_name}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Authenticate GCS
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{secrets.DEV_KEY_FILE}}"
      - name: Deploy to Google Cloud Storage
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "build"
          destination: "${{vars.BUCKET_NAME}}"
          parent: false
